### ISSUE TITLE
文中的二值变化检测分支是否存在问题，以及架构的图中的mask操作在代码中似乎并没有实现？希望作者能够进行解答

### ISSUE THREAD

**Issue by Gy-X** [DingLei14/Bi-SRNet#36]
![公式问题](https://github.com/user-attachments/assets/3921b2dc-38e4-4a56-bd7a-3b72c3be9db9)
在文中针对变化检测分支:优化时使用的标签为L1的非零区域生成的(我查看你的源码发现的)，这样子的设计似乎从底层就不合理，因为L1的非零区域并不等同于变化区域。
![mask](https://github.com/user-attachments/assets/095609d8-9f47-4260-84b9-ed4b2cb8be99)
![针对变化区域计算语义损失](https://github.com/user-attachments/assets/d2e7d6e3-571d-45b0-9cc6-58769adb4086)

针对我标红的地方似乎在你的源码中并没有找到相关的操作，从你文中的描述中我看到了你确实期望去使用mask，去滤除掉非变化区域的语义分割损失计算，但是我翻了你的源码似乎并没有找到相关实现，希望作者能进行解答？下面是你的网络部分前向传播的源码，可以看到你的变化检测分支和两个语义分割的分支完全是独立的两个分支，并没有任何交互。
![code](https://github.com/user-attachments/assets/e7bef8dd-ac3f-4016-b11b-52c2d21a2a8f)

**Comment by DingLei14** [comment]
masking操作在推理代码中
